# Generated by Django 2.2.6 on 2019-10-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_guitarakk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitarakk',
            old_name='title',
            new_name='name',
        ),
    ]
