# Generated by Django 2.2.6 on 2019-10-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20191010_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarEl',
            fields=[
                ('guitarakk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.GuitarAkk')),
            ],
            bases=('app1.guitarakk',),
        ),
        migrations.AddField(
            model_name='guitarakk',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
