# Generated by Django 2.2.6 on 2019-10-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20191010_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitarakk',
            name='color',
        ),
        migrations.DeleteModel(
            name='GuitarEl',
        ),
    ]
