# Generated by Django 2.2.6 on 2019-10-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img_equipments/'),
        ),
        migrations.AddField(
            model_name='guitarakk',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img_guitar/'),
        ),
        migrations.AddField(
            model_name='guitarel',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img_elguitar/'),
        ),
        migrations.AddField(
            model_name='key',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img_keys/'),
        ),
    ]
